### ISSUE TITLE
Task Router Workflow Configuration 

### ISSUE THREAD

**Issue by joshhornby** [kevinburke/twilio-go#30]
I'm looking into building the [TaskRouter Workflow API](https://www.twilio.com/docs/taskrouter/api/workflows#action-create) into this package.

The endpoint takes a `Configuration` parameter which is a JSON encoded string, but in reality we can build a structured type from this string. The string must look like:

```
{
    "task_routing": {
        "default_filter": {
            "queue": "WQXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        },
        "filters": [
            {
                "expression": "type=='sales'",
                "targets": [
                    {
                        "queue": "WQXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                    }
                ]
            },
            {
                "expression": "type=='marketing'",
                "targets": [
                    {
                        "queue": "WQXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                        "expression": "task.foo == worker.foo" <-- This is optional 
                    }
                ]
            },
            {
                "expression": "type=='support'",
                "targets": [
                    {
                        "queue": "WQXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                    }
                ]
            }
        ]
    }
}
```

I'm looking for some advice/help in how we can model this Go side, I think we should force a user into building valid configurations and not allow them to pass in a simple json string.

**Comment by kevinburke** [comment]
The API should accept `url.Values`, I think. I'm reluctant to special case this. Twilio accepts JSON because (I believe) they might change the format later. We shouldn't lock library users into a particular format or have the potential to have stricter validation on the client than the server is doing, we should just send to the server and let the server validate.

We could add a helper function for validating JSON with the caveat that this is valid as of X date and the API may have changed since then.

**Comment by kevinburke** [comment]
Going to close this. Thanks for all of your work on the library!

**Comment by joshhornby** [comment]
Reading back I agree with your points, not the responsibility of the library. And happy to help, thanks for all your help on the PRs.
